Apply table styling to all tables in td-content, not just direct chil…
google/docsy pull request #1017
Opened 2022-05-23 13:01 UTC by NatasaKralj

As stated in https://github.com/google/docsy/issues/883, tables were not being styled properly in `<details><summary>` blocks. I found the same issue to affect tables nested in list elements. 
Removing `>` from the table entry enables proper styling to be applied to any table element that's a child of `td-content`.

2022-06-20 16:45 UTC, geriom requested changes
Thank you @NatasaKralj 

Looking at the SCSS file, I think other elements can benefit from the same fix. Would you mind also removing the `>` selector from `blockquote`, `ul li` and `ol li`?

2022-08-06 16:39 UTC, chipzoller commented
@NatasaKralj it would be great to get this PR accepted as it'll really help us.

2022-08-10 11:00 UTC, NatasaKralj commented
@chipzoller Apologies for the late response. I am trying to sort out signing the Google CLA before updating the PR. Hopefully I will resolve this soon, otherwise I will submit another PR from my personal account.

2022-10-03 12:47 UTC, chipzoller commented
Any updates here? This PR would really help us.

2022-10-05 15:44 UTC, NatasaKralj commented
Hello, apologies again for the long wait time.

I created a [new PR](https://github.com/google/docsy/pull/1255) from my personal GH account (where I could freely sign the Google CLA). The new PR has `>` removed from additional elements, as requested by @geriom.
I'm closing this one.

2022-10-05 15:44 UTC, closed without merging