WIP: split Navigation and Search pages
google/docsy pull request #1352
Opened 2023-01-09 15:46 UTC by LisaFC

Fixes #1047

2023-01-09 16:03 UTC, LisaFC commented
Work so far splits the pages and fixes the couple of internal links that the split broke. There *is* also the possibility of it breaking external links, though sadly I'm pretty sure you can't redirect to/from anchors....

2023-03-08 12:47 UTC, chalin reviewed
Thanks for working on this. See inline for a few nits.

2023-03-08 12:47 UTC, chalin commented on userguide/content/en/docs/adding-content/navigation.md
> +title: "Navigation and Menus"
```suggestion
title: Navigation and Menus
```

2023-03-08 12:47 UTC, chalin commented on userguide/content/en/docs/adding-content/navigation.md
> +   Customize site navigation for your Docsy site.
```suggestion
description: Customize site navigation for your Docsy site.
```

2023-03-08 12:47 UTC, chalin commented on userguide/content/en/docs/adding-content/search.md
> +title: "Search"
```suggestion
title: Search
```

2023-03-08 14:01 UTC, LisaFC commented
Don't think there's anything else I need to do here so I am un-WIP-ing it. @chalin @geriom @emckean want to take a look?

2023-03-08 14:14 UTC, chalin commented
LGTM aside from the nits identified above. The link checker seems happy, so that's good. (The issue of title font color on the homepage is fixed via #1467, FYI.)

2023-06-12 18:50 UTC, deining approved these changes
LGTM

2023-07-13 13:06 UTC, chalin requested changes
The new Search page is missing changes that were applied to the "Site search options" section since this PR was created: the most obvious are the updates to the config file names, but there could be more. @LisaFC - did you recopy the "Site search options" section from `@HEAD`?

2023-07-13 15:35 UTC, LisaFC commented
I thought I did but possibly it got lost in the merge. Let me add those in again. Thanks for spotting!

2023-07-13 15:59 UTC, LisaFC commented
Hang on, I've realized they're in the intro, which I didn't change because I rewrote it. Let me fix the file names.

2023-07-13 16:35 UTC, chalin approved these changes
LGTM, thanks!

2023-07-13 16:37 UTC, merged