layouts: split footer partial in several partials
google/docsy pull request #1500
Opened 2023-04-21 09:28 UTC by yann-soubeyrand

This allows to more easily override some parts of the footer.

2023-04-21 12:30 UTC, deining requested changes
In general, I'm fine with these changes. Directory `layouts/partials` contains a lot of file already, therefore I would propose to create a new directory `layouts/partials/footer` and put the newly introduced files `foooter-xxx.html`into that directory.

2023-04-21 14:12 UTC, yann-soubeyrand commented
That’s indeed a good idea!

2023-04-21 14:52 UTC, yann-soubeyrand commented on layouts/partials/footer.html
>        <div class="col-6 col-sm-4 text-xs-center order-sm-2">
Shouldn’t it be `order-sm-1` here?

2023-04-21 17:20 UTC, yann-soubeyrand commented on layouts/partials/footer.html
>        <div class="col-6 col-sm-4 text-xs-center order-sm-2">
I think it’s a typo and I fixed it in my PR.

2023-05-14 10:20 UTC, fekete-robert commented
That's just what I was looking for, I hope it gets merged soon. Thanks!

2023-05-15 04:42 UTC, deining approved these changes
LGTM now.

2023-05-31 14:52 UTC, chalin commented
Hi @yann-soubeyrand: thanks for this. I'm eager to look at it once the BS v5.2 upgrade is done and the next release of Docsy is out. Could you resolve conflicts in the meantime? Thanks!

2023-05-31 16:24 UTC, yann-soubeyrand commented
Hi @chalin, it’s done :wink:

2024-02-02 15:03 UTC, chalin approved these changes
Great! ✨

2024-02-02 15:03 UTC, merged