Auto-sync vendor assets & Hugo module versions + copyedits to README and CONTRIBUTING
google/docsy pull request #1725
Opened 2023-11-10 22:46 UTC by chalin

- Followup to #1217
- Fixes #1182
- Fixes #1723
- Creates a single `assets/_vendor` folder to hold all missing vendor assets (which for now only contains the bootstrap vendor file)
- Adds a script to sync the BS vendor file(s) from the BS NPM package, triggered by a post-install event
- Adds a script to sync Hugo modules based on the corresponding NPM package versions. Hence the NPM version are canonical
- Updates `CONTRIBUTING.md`:
  - Simplifies the steps in **Publishing a release** since some changes are not handled automatically. Also removed references to the `dependencies` module that was dropped via #1217
  - Other tweaks
- Explicit mention of code-of-conduct in README and `CONTRIBUTING.md`
- Closes #1724 by superseding it (I needed to commit to the docsy repo so that I could test from the PR branch)

2023-11-10 22:53 UTC, chalin commented
@deining - I've tested this using `docsy-example`, fetching the commit from the branch of this PR, and it works AFAICT.

2023-11-12 20:10 UTC, deining requested changes
Spotted a typo which needs to be corrected.
LGTM otherwise, haven't tested it, though.

2023-11-12 22:32 UTC, merged

2023-11-12 22:38 UTC, chalin commented
Oh dang, tripped on the buttons somehow (or was it GH Desktop?). Anyhow, I didn't mean to merge this yet. I'll fix the typo in a followup commit.

2023-11-12 22:41 UTC, chalin commented
Yeah, it wasn't the GH interface that did the merge, because it didn't squash the commits, which I have enabled by default. It must have been the GH desktop. :-(

2023-11-12 22:42 UTC, chalin commented
My typo fix even made it into main!

2023-11-12 22:42 UTC, chalin commented on assets/_vendor/README.md
> +automatically synchronized as installation time.
Yes, thanks! Fixed.

2023-11-12 22:45 UTC, chalin commented
Ok, I've reverted the commit and will resubmit a PR.