User guide: use docsy as module (in workspace)
google/docsy pull request #1731
Opened 2023-11-12 17:32 UTC by deining

After having #1217 merged, the user guide cannot built successfully using `hugo --themesDir ../..` any more. This PR fixes this by pulling in docsy as a hugo module when building or previewing the user guide. In the module definition inside `userguide/hugo.yaml`, there is a workspace definition in place so that docsy is pulled in from the local docsy sources in the repo root level). Previewing the user guide is now as easy as:

```
cd userguide
hugo server
```

2023-11-12 23:10 UTC, chalin requested changes
But our CI / Netlify build actions use `hugo --themesDir ../..` and the build process is running fine. E.g., this is the latest production build, https://app.netlify.com/sites/docsydocs/deploys/655157197e81260008cee338:

```powershell
...
5:52:39 PM: > build:production
5:52:39 PM: > npm run _hugo -- --minify
5:52:40 PM: > _hugo
5:52:40 PM: > hugo --cleanDestinationDir --themesDir ../.. --minify
5:52:40 PM: Start building sites …
5:52:40 PM: hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df+extended linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio
5:52:42 PM:                    | EN
5:52:42 PM: -------------------+-----
5:52:42 PM:   Pages            | 81
5:52:42 PM:   Paginator pages  |  0
5:52:42 PM:   Non-page files   |  8
5:52:42 PM:   Static files     | 35
5:52:42 PM:   Processed images |  5
5:52:42 PM:   Aliases          |  3
5:52:42 PM:   Sitemaps         |  1
5:52:42 PM:   Cleaned          |  0
5:52:42 PM: Total in 1767 ms
5:52:42 PM: > postbuild:production
5:52:42 PM: > npm run _check:links
...
```

The build works locally as well for me. Is there something I'm missing?

2023-11-13 00:04 UTC, deining commented
> The build works locally as well for me.

Yes, but only if you are using npm for the build. Then two directories will be created prior to build process via this directive:

https://github.com/google/docsy/blob/8e9cb3c722ca2e62666ee2d493e662a86c80809d/package.json#L10

How to repoduce the error I'm referring to:

Run `hugo server` directly inside the folder `userguide` of the repo (that's what I'm regularly doing) and you are in trouble:

```
git clone https://github.com/google/docsy.git
cd userguide/
hugo server
...
Error: command error: failed to load modules: module "docsy" not found in "/home/andreas/docsy/userguide/themes/docsy"; either add it as a Hugo Module or store it in "/home/andreas/docsy/userguide/themes".: module does not exist
```

2023-11-13 00:33 UTC, deining commented
After some tweaking, the user guide can be now build successfully via:

- npm (netlify)
- npm run serve (local)
- hugo server (local)

2023-11-13 06:35 UTC, deining commented
Just realized that with this PR in place, we can simplify `package.json` a bit. Done in second commit 31aeeb3b7c6d5014858b8bb34fe06a91f4887d6c.

2023-11-13 10:07 UTC, chalin requested changes
Thanks for exploring this, but this PR **breaks the builds** of projects that don't use Docsy as a Hugo module because of the removal of the `_mkdir:hugo-mod` script.

---

As for switching to Hugo modules for the User Guide, the PSC decided against that in February of this year, back when Docsy support for Hugo modules was introduced. For some context, see the thread starting at @LisaFC's comment https://github.com/google/docsy/pull/871#issuecomment-1036278297.
 
Part of the reasoning was that the Docsy example would use Hugo modules and the UG would not. With such a setup we have **CI of two repos** each **testing out alternative Docsy usage scenarios**.

I can bring up the issue again at the next PSC meeting if you'd like, but the reasons for doing it the way it is now still hold.

/cc @geriom @emckean

2023-11-16 22:44 UTC, chalin commented
> As for switching to Hugo modules for the User Guide, the PSC decided against that in February of this year, back when Docsy support for Hugo modules was introduced. For some context, see the thread starting at @LisaFC's comment [#871 (comment)](https://github.com/google/docsy/pull/871#issuecomment-1036278297).

The PSC during today's meeting upheld the preference to _not_ have the User Guide as a module. /cc @LisaFC @emckean @geriom. Closing.

2023-11-16 22:44 UTC, closed without merging