Fix links for single language sites
google/docsy pull request #1744
Opened 2023-11-16 16:21 UTC by LisaFC

Fixes #981
Fixes #138

Requires Hugo 0.112.0

2023-11-16 16:22 UTC, LisaFC commented
See discussion with @lyind in #1486

2023-11-16 16:40 UTC, chalin requested changes
This breaks the page-meta links for some pages on the OTel website, for example the [mission](https://opentelemetry.io/community/mission/) page. I'll investigate further as soon as I can.

2023-11-16 17:21 UTC, chalin commented
@LisaFC et al. - do you have a reference to a public site that exhibits the broken page-meta links? Or do you have a simple test case to reproduce the problem?

2023-11-16 17:26 UTC, chalin commented
Ah, nm, found one :)

2023-11-16 18:08 UTC, chalin commented on layouts/partials/page-meta-links.html
> +{{ $pathFormatted := strings.TrimPrefix hugo.WorkingDir $.File.Filename -}}
The line your are changing was added in support of builds under Windows:

- #163

Removing the line will introduce a regression IMHO.

2023-11-16 18:23 UTC, LisaFC commented
Ok, let me take a further look

2023-11-16 18:50 UTC, LisaFC commented
If you remove the overridden partial in this project you should see the problem: https://github.com/LisaFC/monolang

2023-11-17 22:43 UTC, chalin commented
I got the monolang repo working with Docsy at HEAD (using simple front matter) but, regardless, I'm feeling that your fix is the right way to go! 🎉  I have a tweaked version locally, and will share it + more feedback when I'm back.

2024-02-01 14:26 UTC, chalin approved these changes
Great work! This definitely seems like the right way to fix this. There is some cleanup in the code that I'd like to do, but I'll address that in a followup PR, and add a statement about this being a breaking change to the CHANGELOG.

2024-02-01 14:26 UTC, chalin commented on layouts/partials/page-meta-links.html
> +{{ $pathFormatted := strings.TrimPrefix hugo.WorkingDir $.File.Filename -}}
Actually, our tests are passing under windows, so I'll assume that this is still ok. If not, we can address the regression later.

2024-02-01 14:26 UTC, merged