Change navbar search border colour to make it stand out
google/docsy pull request #635
Opened 2021-07-16 10:35 UTC by at055612

Currently the navbar search input has border `none` so you just see a hint of the drop shadow.  As the input text is shorter than the input it looks like there is a lot of empty space to the right of it.  

Before the change it looks like 

![image](https://user-images.githubusercontent.com/22818309/125934640-7ebc0f11-abb0-49a3-8a6d-3b0fb6772c9b.png)

After the change it looks like

![image](https://user-images.githubusercontent.com/22818309/125934820-05b979b1-84f7-4ea7-a513-c2b1daa4773d.png)

2021-07-16 15:21 UTC, LisaFC commented
I like it, though I wonder should we make it an option rather than the default? Anyone else?

2021-07-17 10:19 UTC, narrenfrei commented
I've also changed the lookout from this search input in our docs a little bit. You can have a look at this test page:
https://60f2abac014e3400078b4632--sad-volhard-b41b3b.netlify.app

This example has 3 changes to the current official version:

1. make the search input a little bit more visable
2. let the placeholder visible until typing in something (like in the sidebar)
3. give the language dropdown in the sidebar (on smaller devices) a little bit more padding

The version of @at055612 is also OK for me and in my opinion better the the current search input. I would make it as Docsy default if you merge it.

2021-07-21 14:50 UTC, LisaFC commented
I like them both but I think I like @narrenfrei's version slightly better. Anyone else?

2021-07-22 08:37 UTC, at055612 commented
I'm happy with @narrenfrei's version.  A bit more subtle.  As long as the border can be seen I am ok.

2022-02-02 15:25 UTC, Jassi10000 requested changes
@at055612 
Buddy you must resolve the merge conflicts before you make a PR

2022-02-02 15:34 UTC, at055612 commented
> @at055612 Buddy you must resolve the merge conflicts before you make a PR

The PR was not in conflict when created.  It is now but I was waiting on a decision from the maintainers whether to proceed with this PR or for @narrenfrei's change to be used instead.

2022-02-02 15:51 UTC, chalin commented
My vote is to preserve the current default. Projects can easily customize this to their own tastes.

2022-08-02 19:56 UTC, prdsoftware commented
The new version of Algolia has different styling for the search box that makes it stand out by default.

2026-08-15 12:28 UTC, chalin commented
- Pre-0.17.0 triage campaign: #2717
- Made moot by the later search-box restyling (noted in-thread, 2022). Thanks.

2026-08-15 12:28 UTC, closed without merging