Update fr.toml
google/docsy pull request #928
Opened 2022-03-12 08:11 UTC by arnaudlevy

2022-03-14 19:12 UTC, chalin requested changes
Merci pour l'ajout. Par contre, je préfère le texte "Afficher la source de la page". (Oui, c'est plus long 🤷🏼‍♂️)

2022-04-09 16:06 UTC, arnaudlevy commented
Oui, bonne idée ! C'est plus clair et la place ne manque pas.

2022-04-20 06:43 UTC, Flashpok commented
Bonjour, j'espère n'être pas complètement hors sujet (si c'est le cas je m'en excuse).
Accepteriez-vous de m'expliquer en quelques mots quand la demande d'ajout de traduction sera effectivement ajoutée à docsy ? (je débute dans Github). Faut-il attendre une prochaine version de docsy ou c'est implémenté directement ? (je pose la question car je n'ai pas encore accès à cet ajout de traduction sur mon site).
En vous remerciant bien cordialement,
C.

2022-05-06 11:51 UTC, arnaudlevy commented
Bonjour @chalin ! J'ai fait mais dans une autre pr, pardon
https://github.com/google/docsy/pull/1003

2022-06-29 20:33 UTC, chalin commented
Superseded by #1003.

No worries @arnaudlevy, and thanks for the updated PR.

> ensuite ça sortira dans la prochaine release si j'ai bien compris

Oui, c'est ça.

2022-06-29 20:33 UTC, closed without merging